export interface ParkData {
  id: string;
  name_uz: string;
  name_ru: string;
  name_en: string;
  desc_uz: string;
  desc_ru: string;
  desc_en: string;
  coverUrl: string;
  lat: number;
  lng: number;
  has360: boolean;
  type: string;
  district: string;
}

export const ALL_PARKS: ParkData[] = [
  {
    id: "botanika",
    name_uz: "Botanika Bog'i",
    name_ru: "Ботанический Сад",
    name_en: "Botanical Garden",
    desc_uz: "Toshkent shahridagi eng katta va sokin tabiat maskani. Turli xil o'simliklar va daraxtlar bilan qoplangan yashil hudud.",
    desc_ru: "Самый большой и тихий природный парк в Ташкенте. Зеленая территория с разнообразными растениями и деревьями.",
    desc_en: "The largest and quietest nature park in Tashkent. A green area covered with various plants and trees.",
    coverUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3411,
    lng: 69.3138,
    has360: true,
    type: "tabiat",
    district: "Mirzo Ulug'bek"
  },
  {
    id: "islamic-center",
    name_uz: "Islom Sivilizatsiyasi Markazi",
    name_ru: "Центр Исламской Цивилизации",
    name_en: "Center of Islamic Civilization",
    desc_uz: "O'zbekistonning boy tarixiy va islom madaniyatini aks ettiruvchi ulug'vor me'moriy majmua.",
    desc_ru: "Величественный архитектурный комплекс, отражающий богатую историческую и исламскую культуру Узбекистана.",
    desc_en: "A majestic architectural complex reflecting the rich historical and Islamic culture of Uzbekistan.",
    coverUrl: "https://images.unsplash.com/photo-1550184658-ff6132a71714?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3325,
    lng: 69.2434,
    has360: true,
    type: "madaniy",
    district: "Olmazor"
  },
  {
    id: "ecopark",
    name_uz: "Eko Park",
    name_ru: "Эко Парк",
    name_en: "Eco Park",
    desc_uz: "Sport va faol dam olish uchun mo'ljallangan zamonaviy ekologik park.",
    desc_ru: "Современный экологический парк, предназначенный для спорта и активного отдыха.",
    desc_en: "A modern ecological park designed for sports and active recreation.",
    coverUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3115,
    lng: 69.2933,
    has360: true,
    type: "sport",
    district: "Mirzo Ulug'bek"
  },
  {
    id: "central-park",
    name_uz: "Markaziy bog' (Telman)",
    name_ru: "Центральный парк (Тельмана)",
    name_en: "Central Park",
    desc_uz: "Shaharning eng mashhur oilaviy dam olish maskanlaridan biri. Attraksionlar va soyali daraxtzorlar mavjud.",
    desc_ru: "Один из самых популярных парков для семейного отдыха в городе. Есть аттракционы и тенистые деревья.",
    desc_en: "One of the most popular family recreation parks in the city. Features attractions and shady trees.",
    coverUrl: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3105,
    lng: 69.2965,
    has360: false,
    type: "klassik",
    district: "Mirzo Ulug'bek"
  },
  {
    id: "milliy-bog",
    name_uz: "Alisher Navoiy Milliy Bog'i",
    name_ru: "Национальный парк им. Алишера Навои",
    name_en: "Alisher Navoi National Park",
    desc_uz: "Katta ko'llar, qayiqlar va sokin yashil hududlarga ega shahar markazidagi ulkan park.",
    desc_ru: "Огромный парк в центре города с большими озерами, лодками и тихими зелеными зонами.",
    desc_en: "A huge park in the city center with large lakes, boats, and quiet green areas.",
    coverUrl: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3039,
    lng: 69.2458,
    has360: false,
    type: "klassik",
    district: "Chilonzor"
  },
  {
    id: "magic-city",
    name_uz: "Magic City",
    name_ru: "Magic City",
    name_en: "Magic City",
    desc_uz: "Butun oila uchun ko'ngilochar shaharcha. Dunyo me'morchiligi namunalari va zamonaviy attraksionlar.",
    desc_ru: "Развлекательный городок для всей семьи. Образцы мировой архитектуры и современные аттракционы.",
    desc_en: "An entertainment city for the whole family. Examples of world architecture and modern attractions.",
    coverUrl: "https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3030,
    lng: 69.2465,
    has360: false,
    type: "kongilochar",
    district: "Chilonzor"
  },
  {
    id: "tashkent-city-park",
    name_uz: "Tashkent City Park",
    name_ru: "Ташкент Сити Парк",
    name_en: "Tashkent City Park",
    desc_uz: "Shaharning markaziy va eng zamonaviy parklaridan biri. Favvoralar shousi bilan mashhur.",
    desc_ru: "Один из центральных и самых современных парков города. Известен шоу фонтанов.",
    desc_en: "One of the central and most modern parks in the city. Famous for its fountain shows.",
    coverUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3142,
    lng: 69.2492,
    has360: false,
    type: "zamonaviy",
    district: "Yunusobod"
  },
  {
    id: "anhor-lokomotiv",
    name_uz: "Anhor-Lokomotiv",
    name_ru: "Анхор-Локомотив",
    name_en: "Ankhor-Lokomotiv",
    desc_uz: "Ekstremal attraksionlar, O'zbekistondagi eng katta charxpalak va go-karting maydonchasi.",
    desc_ru: "Экстремальные аттракционы, самое большое колесо обозрения в Узбекистане и картинг.",
    desc_en: "Extreme attractions, the largest Ferris wheel in Uzbekistan, and a go-kart track.",
    coverUrl: "https://images.unsplash.com/photo-1563904092230-7ec217b65fe2?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3283,
    lng: 69.2619,
    has360: false,
    type: "attraksion",
    district: "Shayhontohur"
  },
  {
    id: "yapon-bogi",
    name_uz: "Yapon Bog'i",
    name_ru: "Японский Сад",
    name_en: "Japanese Garden",
    desc_uz: "Zen uslubidagi sokin va ko'rkam bog'. Tabiat bilan yolg'iz qolish uchun eng mos maskan.",
    desc_ru: "Тихий и живописный сад в стиле Дзен. Идеальное место для уединения с природой.",
    desc_en: "A quiet and picturesque Zen-style garden. The perfect place to be alone with nature.",
    coverUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3392,
    lng: 69.2818,
    has360: false,
    type: "tabiat",
    district: "Mirzo Ulug'bek"
  },
  {
    id: "ashxobod",
    name_uz: "Ashxobod Sayilgohi",
    name_ru: "Парк Ашхабад",
    name_en: "Ashgabat Park",
    desc_uz: "Zamonaviy va yorqin attraksionlarga boy yirik ko'ngilochar park.",
    desc_ru: "Крупный развлекательный парк, богатый современными и яркими аттракционами.",
    desc_en: "A large amusement park rich in modern and bright attractions.",
    coverUrl: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?q=80&w=1000&auto=format&fit=crop",
    lat: 41.2954,
    lng: 69.3090,
    has360: false,
    type: "attraksion",
    district: "Yashnobod"
  },
  {
    id: "gafur-gulom",
    name_uz: "G'afur G'ulom (Dream Park)",
    name_ru: "Парк им. Гафура Гуляма (Dream Park)",
    name_en: "Gafur Gulyam Park (Dream Park)",
    desc_uz: "Bolalar va oilalar uchun sevimli maskan, yaqinda yangilangan zamonaviy attraksionlar mavjud.",
    desc_ru: "Любимое место для детей и семей, недавно обновленные современные аттракционы.",
    desc_en: "A favorite place for children and families, with recently updated modern attractions.",
    coverUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?q=80&w=1000&auto=format&fit=crop",
    lat: 41.2785,
    lng: 69.2155,
    has360: false,
    type: "attraksion",
    district: "Chilonzor"
  },
  {
    id: "navruz",
    name_uz: "Navro'z Etnografik Bog'i",
    name_ru: "Этнографический парк Навруз",
    name_en: "Navruz Ethnographic Park",
    desc_uz: "O'zbekistondagi barcha viloyatlar me'morchiligi, madaniyati va hunarmandchiligini o'ziga jamlagan milliy bog'.",
    desc_ru: "Национальный парк, объединяющий архитектуру, культуру и ремесла всех регионов Узбекистана.",
    desc_en: "A national park uniting the architecture, culture, and crafts of all regions of Uzbekistan.",
    coverUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3260,
    lng: 69.2630,
    has360: false,
    type: "madaniy",
    district: "Shayhontohur"
  },
  {
    id: "yangi-ozbekiston",
    name_uz: "Yangi O'zbekiston Bog'i",
    name_ru: "Парк Новый Узбекистан",
    name_en: "New Uzbekistan Park",
    desc_uz: "Keng maydonli va eng zamonaviy yirik istirohat bog'i. Tarixiy monumentlar va dam olish zonalari mavjud.",
    desc_ru: "Самый современный и крупный парк с большой территорией. Есть исторические памятники и зоны отдыха.",
    desc_en: "The most modern and largest park with a large territory. Features historical monuments and recreation areas.",
    coverUrl: "https://images.unsplash.com/photo-1570125909517-53cb21c89ff2?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3415,
    lng: 69.4578,
    has360: false,
    type: "zamonaviy",
    district: "Mirzo Ulug'bek"
  },
  {
    id: "victory-park",
    name_uz: "G'alaba Bog'i",
    name_ru: "Парк Победы",
    name_en: "Victory Park",
    desc_uz: "Ikkinchi Jahon urushi qatnashchilariga bag'ishlangan katta tarixiy-memorial yashil majmua.",
    desc_ru: "Большой историко-мемориальный зеленый комплекс, посвященный участникам Второй мировой войны.",
    desc_en: "A large historical and memorial green complex dedicated to the participants of the Second World War.",
    coverUrl: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3530,
    lng: 69.2225,
    has360: false,
    type: "madaniy",
    district: "Olmazor"
  },
  {
    id: "tashkentland",
    name_uz: "Toshkentlend",
    name_ru: "Ташкентленд",
    name_en: "Tashkentland",
    desc_uz: "Bolalar uchun turli karusellar, 'Gorkalar' va kanat yo'llari bor katta attraksionlar maskani.",
    desc_ru: "Большой парк аттракционов для детей с различными каруселями, горками и канатными дорогами.",
    desc_en: "A large amusement park for children with various carousels, slides, and cable cars.",
    coverUrl: "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3408,
    lng: 69.2805,
    has360: false,
    type: "attraksion",
    district: "Yunusobod"
  },
  {
    id: "zoo",
    name_uz: "Toshkent Hayvonot Bog'i",
    name_ru: "Ташкентский Зоопарк",
    name_en: "Tashkent Zoo",
    desc_uz: "Minglab hayvonlar turlarini o'zida jamlagan katta va yashil hayvonot bog'i.",
    desc_ru: "Большой зеленый зоопарк, в котором собраны тысячи видов животных.",
    desc_en: "A large green zoo with thousands of animal species.",
    coverUrl: "https://images.unsplash.com/photo-1456926631375-92c8ce872def?q=80&w=1000&auto=format&fit=crop",
    lat: 41.3465,
    lng: 69.3174,
    has360: false,
    type: "hayvonot",
    district: "Yunusobod"
  },
  {
    id: "flowers-garden",
    name_uz: "Flowers Garden Park",
    name_ru: "Flowers Garden Park",
    name_en: "Flowers Garden Park",
    desc_uz: "10 gektar maydonda joylashgan minglab turdagi gullarga boy go'zal bog'.",
    desc_ru: "Красивый сад с тысячами видов цветов, расположенный на 10 гектарах.",
    desc_en: "A beautiful garden with thousands of types of flowers, located on 10 hectares.",
    coverUrl: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?q=80&w=1000&auto=format&fit=crop",
    lat: 41.2225,
    lng: 69.2150,
    has360: false,
    type: "tabiat",
    district: "Sergeli"
  },
  {
    id: "yoshlar-bogi",
    name_uz: "Yoshlar Bog'i",
    name_ru: "Парк Молодежи",
    name_en: "Youth Park",
    desc_uz: "Yoshlar uchun mo'ljallangan yirik amfiteatr, suzish havzasi va sport zonalari.",
    desc_ru: "Крупный амфитеатр, бассейн и спортивные зоны для молодежи.",
    desc_en: "A large amphitheater, swimming pool, and sports zones designed for youth.",
    coverUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop",
    lat: 41.2330,
    lng: 69.2300,
    has360: false,
    type: "sport",
    district: "Sergeli"
  },
  {
    id: "lokomotiv",
    name_uz: "Lokomotiv Istirohat Bog'i",
    name_ru: "Парк Локомотив",
    name_en: "Lokomotiv Park",
    desc_uz: "Mirzo Ulug'bek tumanidagi qulay va ko'rkam oilaviy attraksionlar majmuasi.",
    desc_ru: "Уютный и красивый семейный комплекс аттракционов в Мирзо-Улугбекском районе.",
    desc_en: "A cozy and beautiful family attractions complex in the Mirzo Ulugbek district.",
    coverUrl: "https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?q=80&w=1000&auto=format&fit=crop", 
    lat: 41.3410,
    lng: 69.3400,
    has360: false,
    type: "attraksion",
    district: "Mirzo Ulug'bek"
  }
];
